/**
 * Textos de las pantallas recreadas de Oquea (app del buceador, modo centro y consola de escritorio) en los cuatro
 * idiomas de la consola. El español es la fuente y define la forma: a los demás les falta una clave o cambia la firma de
 * una función → falla el typecheck. Las frases con datos son funciones (nunca se pegan trozos en la plantilla).
 * No se traducen: la marca (oquea), «Logbook» como nombre de pantalla, nombres de personas y de puntos, niveles de
 * certificación, «Fun dive», «QR» ni las cifras. Lo que llega por props (actividad, punto, vida marina…) ya viene traducido.
 */
export type AppLang = 'es' | 'en' | 'pt' | 'ko';

/** 'ko', 'ko-KR', 'pt-BR'… → idioma de la app; lo que no se conoce, español. */
export function appLang(locale: string | null | undefined): AppLang {
  const l = (locale ?? '').slice(0, 2).toLowerCase();
  return l === 'en' || l === 'pt' || l === 'ko' || l === 'es' ? l : 'es';
}

const es = {
  // Comunes a varias pantallas
  todayActivities: 'Actividades de hoy',
  dive: 'Inmersión',
  seeMedia: 'Ver fotos y vídeos',
  files: (n: string) => `${n} archivos`,
  shareDive: 'Compartir inmersión',
  temperature: 'Temperatura',
  depth: 'Profundidad',
  marineLife: 'Vida marina',
  time: 'Tiempo',
  participants: 'Participantes',
  edit: 'Editar',
  delete: 'Eliminar',
  seeAll: 'Ver todas',
  download: 'Descargar',
  shareLink: 'Compartir enlace',
  share: 'Compartir',
  addPhotos: 'Añadir fotos',
  team: 'Equipo',
  owner: 'Propietario',
  event: 'Evento',
  searchPlaces: 'Busca centros y puntos de inmersión',
  searchDiver: 'Buscar buceador',
  scannedQr: 'Escaneó el QR',
  addedByHand: 'Añadido a mano',
  divesHere: 'Inmersiones aquí',
  first: 'Primera',
  last: 'Última',
  firstDate: '10 jun 2023',
  diveSites: 'Dive sites',
  boatTrip: 'Salida en barco',
  nightDiving: 'Buceo nocturno',
  centreBeach: 'Playa del centro',
  divesN: (n: string) => `${n} inmersiones`,
  diversN: (n: string) => `${n} buceadores`,
  /** «Con {centro}»: pie de las tarjetas para compartir y de la insignia. */
  withName: (name: string) => `Con ${name}`,

  // access (registro)
  signUp: 'Regístrate',
  tagline: 'Todas tus inmersiones en un solo lugar',
  withEmail: 'Continuar con email',
  withGoogle: 'Continuar con Google',
  legal: 'Al entrar, aceptas los Términos y condiciones y la Política de privacidad.',

  // qrActivity (tras escanear el QR)
  saveToLogbook: 'Guardar en mi logbook',
  logInOquea: 'Registra esta inmersión en Oquea',
  cardForSocials: 'Tarjeta para tus redes',
  savedBy: (centre: string) => `Al guardar, ${centre} añadirá esta inmersión a tu historial.`,

  // qrPick (elegir la actividad del día)
  whichActivity: '¿Qué actividad haces hoy?',
  pickDate: 'Jueves, 26 de febrero de 2026',
  tryDive: 'Bautismo de buceo',
  nightDive: 'Inmersión nocturna',
  addedBy: (name: string) => `Añadida por ${name}`,
  notFound: '¿No encuentras tu inmersión?',
  lookEarlier: 'Mira en días anteriores o añádela',

  // diveDetail
  seeMyData: 'Ver mis datos',
  seeOrEdit: 'Ver o editar los datos de la inmersión',
  inCardForSocials: 'En una tarjeta para tus redes',

  // diveSaved
  diveAdded: '¡Inmersión añadida a tu logbook!',
  whatNow: '¿Qué quieres hacer ahora?',
  seeInLogbook: 'Ver en mi logbook',
  shareOnSocials: 'Compartir en tus redes',
  backToActivities: 'Volver a actividades',

  // shareCard (pegatinas de las tarjetas para compartir)
  divingAt: (site: string) => `Buceando en ${site}`,
  min: 'min',
  tempShort: 'Temp.',
  cardDate1: '26 feb 26',
  newRecord: 'Nuevo récord personal',
  maxDepth: 'Profundidad máxima',
  prevRecord: (site: string) => `Récord anterior 38 m · Inmersión #47 · ${site}`,
  cardDate2: '16 sep 26',
  milestone: 'Hito conseguido',
  unitDives: 'inmersiones',
  divingSince: 'Buceando desde 2019 · 34 puntos · 6 países',
  underwater: 'Bajo el agua',
  deepest: 'La más profunda',
  diveNumberAt: (site: string) => `Inmersión 100 en ${site}`,
  theTrip: 'El viaje',
  tripTitle: 'Maldivas 2025',
  divesCap: 'Inmersiones',
  sitesCap: 'Puntos',
  tripLife: 'Mantas · Tiburón ballena · Tortugas',
  cardDate3: 'feb 2025',
  seenIn: 'Visto en el 3 % de las inmersiones',
  whaleShark: 'Tiburón ballena',
  diveNo47: (site: string) => `Inmersión #47 · ${site}`,

  // logbook
  allYears: 'Todos',
  moonDive: 'Inmersión a la luz de la luna',
  lbDate1: '16 sep 2026',
  lbDate2: '12 sep 2026',
  shareThisDive: 'Compartir esta inmersión',

  // diverProfile
  profile: 'Perfil',
  instructor: 'Instructor',
  /** HTML: la cifra va en <em>; `n` llega ya escapado. */
  diveCountHtml: (n: string) => `<em>${n}</em> inmersiones`,
  myStats: 'Mis estadísticas',
  diveTime: 'Tiempo de buceo',
  maxDepthShort: 'Prof. máxima',
  certifications: 'Certificaciones',
  countries: 'Países',
  centres: 'Centros',
  lastDive: 'Última',
  lastDiveDate: 'feb 26',
  myCentres: 'Mis centros',

  // activities (modo centro)
  activities: 'Actividades',
  diveSite: 'Dive site',
  upcoming: 'Próximas actividades',
  owCourse: 'Open Water — curso',
  oneStudent: '1 alumno',
  nextDate: '28 feb',

  // createActivity
  newDive: 'Nueva inmersión',
  presetLoaded: 'Datos del punto, ya cargados',
  maxDepthAbbr: 'Prof. máx.',
  minutes: (n: string) => `${n} min`,
  visibility: 'Visibilidad',
  continue: 'Continuar',

  // centreQr
  qrText: 'Tus buceadores escanean este QR para registrar sus inmersiones y ver las actividades. Descárgalo e imprímelo para el centro o el barco.',
  manageTeam: 'Gestionar equipo',
  editCentre: 'Editar datos del centro',

  // crm (lista y ficha del buceador)
  /** HTML: la cifra va en <b>; `n` llega ya escapado. */
  diversInCentreHtml: (n: string) => `<b>${n}</b> buceadores en tu centro`,
  diverProfile: 'Perfil del buceador',
  seePublicProfile: 'Ver perfil público',
  atYourCentre: 'En tu centro',
  activityHistory: 'Historial de actividades',
  diveAt: (site: string) => `Inmersión — ${site}`,
  recreational: 'Recreativa',
  course: 'Curso',
  courseAdvanced: 'Curso — Advanced',
  histDate2: '24/02/2026',
  histDate3: '03/02/2026',

  // myCentres
  ownerActivities: (n: number) => `Propietario · ${n} actividades`,
  harbour: 'Puerto',
  createCentre: 'Crear nuevo centro',
  noTeam: 'Ahora no formas parte del equipo de ningún centro. Cuando un centro te añada, aparecerá aquí.',

  // team
  roleOwner: 'Owner',
  roleAdmin: 'Admin',
  addMember: 'Añadir miembro',

  // diveSites
  siteMantas: 'Corriente suave · mantas',
  siteWall: 'Pared · tiburones',
  siteCave: 'Cueva · luz',
  addDiveSite: 'Añadir dive site',

  // map y event (mapa con la ficha del marcador)
  eventOn: 'Evento en marcha',
  beachCleanup: 'Limpieza de la playa',
  beachWhen: 'Sáb 14 sep · 09:00',
  seabedCleanup: 'Limpieza de fondos',
  seabedWhen: 'Dom 21 sep · 08:30',
  /** Etiqueta del marcador de la ONG en el mapa: «Mar Limpio ONG». */
  ngoMarker: (name: string) => `${name} ONG`,
  kindCentre: 'Centro de buceo',
  kindNgo: 'ONG',
  kindSite: 'Punto de inmersión',
  kindEvent: 'Evento',
  ctaCentre: 'Ver centro',
  ctaNgo: 'Ver ONG',
  ctaSite: 'Ver punto de inmersión',
  ctaEvent: 'Ver evento',
  organiser: 'Organiza',

  // album
  photosN: (n: string) => `${n} fotos`,
  daysLeft: (n: string) => `Quedan ${n} días`,
  yourPhoto: 'Tu foto',
  follow: 'Seguir',

  // badge
  badgeTitle: 'Insignia de asistencia',
  attended: (date: string) => `Asististe · ${date}`,
  tookPart: (name: string) => `${name} ha participado en este evento.`,

  // nav (barra de abajo) y CenterHead (pestañas del modo centro)
  logbook: 'Logbook',
  tabDives: 'Buceos',
  tabCrm: 'CRM',
  myCentre: 'Mi centro',

  // console (escritorio del centro)
  modeManage: 'Gestión',
  modeDiver: 'Buceador',
  calendar: 'Calendario',
  diveSitesNav: 'Puntos de inmersión',
  activeCentre: 'Centro activo',
  tripsScheduled: '3 salidas programadas',
  seeCentreQr: 'Ver QR del centro',
  createActivity: 'Crear actividad',
  statDivers: 'Buceadores en tu CRM',
  statDives: 'Inmersiones registradas',
  outOf: (a: number, b: number) => `${a} de ${b}`,
  profileComplete: 'Perfil público completo',
  boatFunDive: 'Salida en barco · Fun dive',
  nightFunDive: 'Buceo nocturno · Fun dive',
  participantsN: (n: number) => `${n} participantes`,
  addParticipant: 'Añadir participante',
  noAccount: 'Sin cuenta todavía',
  today: 'Hoy',
  scannedQrPl: 'Escanearon el QR',
  addedByHandPl: 'Añadidos a mano',
  diversVisited: (n: string, centre: string) => `${n} buceadores han pasado por ${centre}`,
  lastDate: '26 feb 2026',
  myCentrePublic: 'Mi centro · perfil público',
  howDiversSeeYou: 'Cómo te ven los buceadores',
  editDetails: 'Editar datos',
  uniqueQr: 'Tu QR único',
  qrWhere: 'Para el barco, el mostrador o la entrada.',
  sitesMore: (site: string) => `${site}, Shark Point y 4 más`,
  staff: '3 instructores · 2 divemasters',
  languages: 'Idiomas',
  units: 'Unidades',
  unitList: 'Metros · bar · °C',
  profileChecklist: ['Sobre el centro', 'Idiomas', 'Ubicación', 'Dive sites', 'Vida marina', 'Equipo', 'Contacto'],
  exampleData: 'Datos de ejemplo',
};

const en: typeof es = {
  todayActivities: "Today's activities",
  dive: 'Dive',
  seeMedia: 'See photos and videos',
  files: (n) => `${n} files`,
  shareDive: 'Share dive',
  temperature: 'Temperature',
  depth: 'Depth',
  marineLife: 'Marine life',
  time: 'Time',
  participants: 'Participants',
  edit: 'Edit',
  delete: 'Delete',
  seeAll: 'See all',
  download: 'Download',
  shareLink: 'Share link',
  share: 'Share',
  addPhotos: 'Add photos',
  team: 'Team',
  owner: 'Owner',
  event: 'Event',
  searchPlaces: 'Search centres and dive sites',
  searchDiver: 'Search divers',
  scannedQr: 'Scanned the QR',
  addedByHand: 'Added manually',
  divesHere: 'Dives here',
  first: 'First',
  last: 'Last',
  firstDate: '10 Jun 2023',
  diveSites: 'Dive sites',
  boatTrip: 'Boat dive',
  nightDiving: 'Night diving',
  centreBeach: "Centre's beach",
  divesN: (n) => `${n} dives`,
  diversN: (n) => `${n} divers`,
  withName: (name) => `With ${name}`,

  signUp: 'Sign up',
  tagline: 'All your dives in one place',
  withEmail: 'Continue with email',
  withGoogle: 'Continue with Google',
  legal: 'By continuing, you accept the Terms and Conditions and the Privacy Policy.',

  saveToLogbook: 'Save to my logbook',
  logInOquea: 'Log this dive in Oquea',
  cardForSocials: 'A card for your socials',
  savedBy: (centre) => `When you save, ${centre} will add this dive to your history.`,

  whichActivity: 'What are you doing today?',
  pickDate: 'Thursday, 26 February 2026',
  tryDive: 'Try scuba',
  nightDive: 'Night dive',
  addedBy: (name) => `Added by ${name}`,
  notFound: "Can't find your dive?",
  lookEarlier: 'Check previous days or add it',

  seeMyData: 'See my data',
  seeOrEdit: 'View or edit your dive data',
  inCardForSocials: 'As a card for your socials',

  diveAdded: 'Dive added to your logbook!',
  whatNow: 'What would you like to do now?',
  seeInLogbook: 'See in my logbook',
  shareOnSocials: 'Share on your socials',
  backToActivities: 'Back to activities',

  divingAt: (site) => `Diving at ${site}`,
  min: 'min',
  tempShort: 'Temp.',
  cardDate1: '26 Feb 26',
  newRecord: 'New personal best',
  maxDepth: 'Max depth',
  prevRecord: (site) => `Previous best 38 m · Dive #47 · ${site}`,
  cardDate2: '16 Sep 26',
  milestone: 'Milestone reached',
  unitDives: 'dives',
  divingSince: 'Diving since 2019 · 34 sites · 6 countries',
  underwater: 'Underwater',
  deepest: 'Deepest',
  diveNumberAt: (site) => `Dive 100 at ${site}`,
  theTrip: 'The trip',
  tripTitle: 'Maldives 2025',
  divesCap: 'Dives',
  sitesCap: 'Sites',
  tripLife: 'Mantas · Whale shark · Turtles',
  cardDate3: 'Feb 2025',
  seenIn: 'Seen on 3% of dives',
  whaleShark: 'Whale shark',
  diveNo47: (site) => `Dive #47 · ${site}`,

  allYears: 'All',
  moonDive: 'Moonlight dive',
  lbDate1: '16 Sep 2026',
  lbDate2: '12 Sep 2026',
  shareThisDive: 'Share this dive',

  profile: 'Profile',
  instructor: 'Instructor',
  diveCountHtml: (n) => `<em>${n}</em> dives`,
  myStats: 'My stats',
  diveTime: 'Dive time',
  maxDepthShort: 'Max depth',
  certifications: 'Certifications',
  countries: 'Countries',
  centres: 'Centres',
  lastDive: 'Last',
  lastDiveDate: 'Feb 26',
  myCentres: 'My centres',

  activities: 'Activities',
  diveSite: 'Dive site',
  upcoming: 'Upcoming activities',
  owCourse: 'Open Water — course',
  oneStudent: '1 student',
  nextDate: '28 Feb',

  newDive: 'New dive',
  presetLoaded: 'Site data, already filled in',
  maxDepthAbbr: 'Max depth',
  minutes: (n) => `${n} min`,
  visibility: 'Visibility',
  continue: 'Continue',

  qrText: 'Your divers scan this QR to log their dives and see your activities. Download it and print it for the centre or the boat.',
  manageTeam: 'Manage team',
  editCentre: 'Edit centre details',

  diversInCentreHtml: (n) => `<b>${n}</b> divers at your centre`,
  diverProfile: 'Diver profile',
  seePublicProfile: 'View public profile',
  atYourCentre: 'At your centre',
  activityHistory: 'Activity history',
  diveAt: (site) => `Dive — ${site}`,
  recreational: 'Recreational',
  course: 'Course',
  courseAdvanced: 'Course — Advanced',
  histDate2: '24/02/2026',
  histDate3: '03/02/2026',

  ownerActivities: (n) => `Owner · ${n} ${n === 1 ? 'activity' : 'activities'}`,
  harbour: 'Harbour',
  createCentre: 'Create new centre',
  noTeam: "You're not on any centre's team yet. When a centre adds you, it will show up here.",

  roleOwner: 'Owner',
  roleAdmin: 'Admin',
  addMember: 'Add member',

  siteMantas: 'Gentle current · mantas',
  siteWall: 'Wall · sharks',
  siteCave: 'Cave · light beams',
  addDiveSite: 'Add dive site',

  eventOn: 'Event on now',
  beachCleanup: 'Beach clean-up',
  beachWhen: 'Sat 14 Sep · 09:00',
  seabedCleanup: 'Seabed clean-up',
  seabedWhen: 'Sun 21 Sep · 08:30',
  ngoMarker: (name) => `${name} NGO`,
  kindCentre: 'Dive centre',
  kindNgo: 'NGO',
  kindSite: 'Dive site',
  kindEvent: 'Event',
  ctaCentre: 'View centre',
  ctaNgo: 'View NGO',
  ctaSite: 'View dive site',
  ctaEvent: 'View event',
  organiser: 'Organised by',

  photosN: (n) => `${n} photos`,
  daysLeft: (n) => `${n} days left`,
  yourPhoto: 'Your photo',
  follow: 'Follow',

  badgeTitle: 'Attendance badge',
  attended: (date) => `You attended · ${date}`,
  tookPart: (name) => `${name} took part in this event.`,

  logbook: 'Logbook',
  tabDives: 'Dives',
  tabCrm: 'CRM',
  myCentre: 'My centre',

  modeManage: 'Manage',
  modeDiver: 'Diver',
  calendar: 'Calendar',
  diveSitesNav: 'Dive sites',
  activeCentre: 'Active centre',
  tripsScheduled: '3 trips scheduled',
  seeCentreQr: 'View centre QR',
  createActivity: 'Create activity',
  statDivers: 'Divers in your CRM',
  statDives: 'Dives logged',
  outOf: (a, b) => `${a} of ${b}`,
  profileComplete: 'Public profile complete',
  boatFunDive: 'Boat dive · Fun dive',
  nightFunDive: 'Night diving · Fun dive',
  participantsN: (n) => `${n} participants`,
  addParticipant: 'Add participant',
  noAccount: 'No account yet',
  today: 'Today',
  scannedQrPl: 'Scanned the QR',
  addedByHandPl: 'Added manually',
  diversVisited: (n, centre) => `${n} divers have been to ${centre}`,
  lastDate: '26 Feb 2026',
  myCentrePublic: 'My centre · public profile',
  howDiversSeeYou: 'How divers see you',
  editDetails: 'Edit details',
  uniqueQr: 'Your unique QR',
  qrWhere: 'For the boat, the front desk or the entrance.',
  sitesMore: (site) => `${site}, Shark Point and 4 more`,
  staff: '3 instructors · 2 divemasters',
  languages: 'Languages',
  units: 'Units',
  unitList: 'Metres · bar · °C',
  profileChecklist: ['About the centre', 'Languages', 'Location', 'Dive sites', 'Marine life', 'Team', 'Contact'],
  exampleData: 'Sample data',
};

const pt: typeof es = {
  todayActivities: 'Atividades de hoje',
  dive: 'Mergulho',
  seeMedia: 'Ver fotos e vídeos',
  files: (n) => `${n} arquivos`,
  shareDive: 'Compartilhar mergulho',
  temperature: 'Temperatura',
  depth: 'Profundidade',
  marineLife: 'Vida marinha',
  time: 'Tempo',
  participants: 'Participantes',
  edit: 'Editar',
  delete: 'Excluir',
  seeAll: 'Ver todas',
  download: 'Baixar',
  shareLink: 'Compartilhar link',
  share: 'Compartilhar',
  addPhotos: 'Adicionar fotos',
  team: 'Equipe',
  owner: 'Proprietário',
  event: 'Evento',
  searchPlaces: 'Busque centros e pontos de mergulho',
  searchDiver: 'Buscar mergulhador',
  scannedQr: 'Escaneou o QR',
  addedByHand: 'Adicionado manualmente',
  divesHere: 'Mergulhos aqui',
  first: 'Primeiro',
  last: 'Último',
  firstDate: '10 jun 2023',
  diveSites: 'Dive sites',
  boatTrip: 'Saída de barco',
  nightDiving: 'Mergulho noturno',
  centreBeach: 'Praia do centro',
  divesN: (n) => `${n} mergulhos`,
  diversN: (n) => `${n} mergulhadores`,
  withName: (name) => `Com ${name}`,

  signUp: 'Cadastre-se',
  tagline: 'Todos os seus mergulhos em um só lugar',
  withEmail: 'Continuar com e-mail',
  withGoogle: 'Continuar com Google',
  legal: 'Ao entrar, você aceita os Termos e Condições e a Política de Privacidade.',

  saveToLogbook: 'Salvar no meu logbook',
  logInOquea: 'Registre este mergulho na Oquea',
  cardForSocials: 'Card para suas redes',
  savedBy: (centre) => `Ao salvar, ${centre} adicionará este mergulho ao seu histórico.`,

  whichActivity: 'Qual atividade você vai fazer hoje?',
  pickDate: 'Quinta-feira, 26 de fevereiro de 2026',
  tryDive: 'Batismo de mergulho',
  nightDive: 'Mergulho noturno',
  addedBy: (name) => `Adicionada por ${name}`,
  notFound: 'Não encontra seu mergulho?',
  lookEarlier: 'Veja os dias anteriores ou adicione',

  seeMyData: 'Ver meus dados',
  seeOrEdit: 'Ver ou editar os dados do mergulho',
  inCardForSocials: 'Em um card para suas redes',

  diveAdded: 'Mergulho adicionado ao seu logbook!',
  whatNow: 'O que você quer fazer agora?',
  seeInLogbook: 'Ver no meu logbook',
  shareOnSocials: 'Compartilhar nas suas redes',
  backToActivities: 'Voltar às atividades',

  divingAt: (site) => `Mergulhando em ${site}`,
  min: 'min',
  tempShort: 'Temp.',
  cardDate1: '26 fev 26',
  newRecord: 'Novo recorde pessoal',
  maxDepth: 'Profundidade máxima',
  prevRecord: (site) => `Recorde anterior 38 m · Mergulho #47 · ${site}`,
  cardDate2: '16 set 26',
  milestone: 'Marco alcançado',
  unitDives: 'mergulhos',
  divingSince: 'Mergulhando desde 2019 · 34 pontos · 6 países',
  underwater: 'Debaixo d’água',
  deepest: 'O mais profundo',
  diveNumberAt: (site) => `Mergulho 100 em ${site}`,
  theTrip: 'A viagem',
  tripTitle: 'Maldivas 2025',
  divesCap: 'Mergulhos',
  sitesCap: 'Pontos',
  tripLife: 'Mantas · Tubarão-baleia · Tartarugas',
  cardDate3: 'fev 2025',
  seenIn: 'Visto em 3% dos mergulhos',
  whaleShark: 'Tubarão-baleia',
  diveNo47: (site) => `Mergulho #47 · ${site}`,

  allYears: 'Todos',
  moonDive: 'Mergulho ao luar',
  lbDate1: '16 set 2026',
  lbDate2: '12 set 2026',
  shareThisDive: 'Compartilhar este mergulho',

  profile: 'Perfil',
  instructor: 'Instrutor',
  diveCountHtml: (n) => `<em>${n}</em> mergulhos`,
  myStats: 'Minhas estatísticas',
  diveTime: 'Tempo de mergulho',
  maxDepthShort: 'Prof. máxima',
  certifications: 'Certificações',
  countries: 'Países',
  centres: 'Centros',
  lastDive: 'Último',
  lastDiveDate: 'fev 26',
  myCentres: 'Meus centros',

  activities: 'Atividades',
  diveSite: 'Dive site',
  upcoming: 'Próximas atividades',
  owCourse: 'Open Water — curso',
  oneStudent: '1 aluno',
  nextDate: '28 fev',

  newDive: 'Novo mergulho',
  presetLoaded: 'Dados do ponto, já preenchidos',
  maxDepthAbbr: 'Prof. máx.',
  minutes: (n) => `${n} min`,
  visibility: 'Visibilidade',
  continue: 'Continuar',

  qrText: 'Seus mergulhadores escaneiam este QR para registrar os mergulhos e ver as atividades. Baixe e imprima para o centro ou o barco.',
  manageTeam: 'Gerenciar equipe',
  editCentre: 'Editar dados do centro',

  diversInCentreHtml: (n) => `<b>${n}</b> mergulhadores no seu centro`,
  diverProfile: 'Perfil do mergulhador',
  seePublicProfile: 'Ver perfil público',
  atYourCentre: 'No seu centro',
  activityHistory: 'Histórico de atividades',
  diveAt: (site) => `Mergulho — ${site}`,
  recreational: 'Recreativo',
  course: 'Curso',
  courseAdvanced: 'Curso — Advanced',
  histDate2: '24/02/2026',
  histDate3: '03/02/2026',

  ownerActivities: (n) => `Proprietário · ${n} ${n === 1 ? 'atividade' : 'atividades'}`,
  harbour: 'Porto',
  createCentre: 'Criar novo centro',
  noTeam: 'Você ainda não faz parte da equipe de nenhum centro. Quando um centro adicionar você, ele aparecerá aqui.',

  roleOwner: 'Proprietário',
  roleAdmin: 'Admin',
  addMember: 'Adicionar membro',

  siteMantas: 'Corrente suave · mantas',
  siteWall: 'Parede · tubarões',
  siteCave: 'Caverna · luz',
  addDiveSite: 'Adicionar dive site',

  eventOn: 'Evento em andamento',
  beachCleanup: 'Limpeza da praia',
  beachWhen: 'Sáb 14 set · 09:00',
  seabedCleanup: 'Limpeza do fundo do mar',
  seabedWhen: 'Dom 21 set · 08:30',
  ngoMarker: (name) => `${name} ONG`,
  kindCentre: 'Centro de mergulho',
  kindNgo: 'ONG',
  kindSite: 'Ponto de mergulho',
  kindEvent: 'Evento',
  ctaCentre: 'Ver centro',
  ctaNgo: 'Ver ONG',
  ctaSite: 'Ver ponto de mergulho',
  ctaEvent: 'Ver evento',
  organiser: 'Organização',

  photosN: (n) => `${n} fotos`,
  daysLeft: (n) => `Faltam ${n} dias`,
  yourPhoto: 'Sua foto',
  follow: 'Seguir',

  badgeTitle: 'Insígnia de participação',
  attended: (date) => `Você participou · ${date}`,
  tookPart: (name) => `${name} participou deste evento.`,

  logbook: 'Logbook',
  tabDives: 'Mergulhos',
  tabCrm: 'CRM',
  myCentre: 'Meu centro',

  modeManage: 'Gestão',
  modeDiver: 'Mergulhador',
  calendar: 'Calendário',
  diveSitesNav: 'Pontos de mergulho',
  activeCentre: 'Centro ativo',
  tripsScheduled: '3 saídas programadas',
  seeCentreQr: 'Ver QR do centro',
  createActivity: 'Criar atividade',
  statDivers: 'Mergulhadores no seu CRM',
  statDives: 'Mergulhos registrados',
  outOf: (a, b) => `${a} de ${b}`,
  profileComplete: 'Perfil público completo',
  boatFunDive: 'Saída de barco · Fun dive',
  nightFunDive: 'Mergulho noturno · Fun dive',
  participantsN: (n) => `${n} participantes`,
  addParticipant: 'Adicionar participante',
  noAccount: 'Ainda sem conta',
  today: 'Hoje',
  scannedQrPl: 'Escanearam o QR',
  addedByHandPl: 'Adicionados manualmente',
  diversVisited: (n, centre) => `${n} mergulhadores já passaram por ${centre}`,
  lastDate: '26 fev 2026',
  myCentrePublic: 'Meu centro · perfil público',
  howDiversSeeYou: 'Como os mergulhadores veem você',
  editDetails: 'Editar dados',
  uniqueQr: 'Seu QR único',
  qrWhere: 'Para o barco, o balcão ou a entrada.',
  sitesMore: (site) => `${site}, Shark Point e mais 4`,
  staff: '3 instrutores · 2 divemasters',
  languages: 'Idiomas',
  units: 'Unidades',
  unitList: 'Metros · bar · °C',
  profileChecklist: ['Sobre o centro', 'Idiomas', 'Localização', 'Dive sites', 'Vida marinha', 'Equipe', 'Contato'],
  exampleData: 'Dados de exemplo',
};

const ko: typeof es = {
  todayActivities: '오늘의 액티비티',
  dive: '다이빙',
  seeMedia: '사진·동영상 보기',
  files: (n) => `파일 ${n}개`,
  shareDive: '다이빙 공유하기',
  temperature: '수온',
  depth: '수심',
  marineLife: '해양 생물',
  time: '시간',
  participants: '참가자',
  edit: '수정',
  delete: '삭제',
  seeAll: '전체 보기',
  download: '다운로드',
  shareLink: '링크 공유',
  share: '공유하기',
  addPhotos: '사진 추가',
  team: '팀',
  owner: '소유자',
  event: '이벤트',
  searchPlaces: '센터와 다이빙 포인트 검색',
  searchDiver: '다이버 검색',
  scannedQr: 'QR 스캔',
  addedByHand: '직접 추가',
  divesHere: '이 센터 다이빙',
  first: '첫 다이빙',
  last: '최근 다이빙',
  firstDate: '2023. 6. 10.',
  diveSites: '다이빙 포인트',
  boatTrip: '보트 다이빙',
  nightDiving: '나이트 다이빙',
  centreBeach: '센터 앞 해변',
  divesN: (n) => `다이빙 ${n}회`,
  diversN: (n) => `다이버 ${n}명`,
  withName: (name) => `with ${name}`,

  signUp: '회원가입',
  tagline: '모든 다이빙 기록을 한곳에',
  withEmail: '이메일로 계속하기',
  withGoogle: 'Google로 계속하기',
  legal: '계속하면 이용약관 및 개인정보 처리방침에 동의하게 됩니다.',

  saveToLogbook: '내 로그북에 저장',
  logInOquea: 'Oquea에 이 다이빙을 기록하세요',
  cardForSocials: 'SNS 공유용 카드',
  savedBy: (centre) => `저장하면 ${centre}에서 이 다이빙을 내 기록에 추가해요.`,

  whichActivity: '오늘 어떤 액티비티를 하나요?',
  pickDate: '2026년 2월 26일 목요일',
  tryDive: '체험 다이빙',
  nightDive: '나이트 다이빙',
  addedBy: (name) => `${name} 님이 추가`,
  notFound: '다이빙을 찾을 수 없나요?',
  lookEarlier: '이전 날짜를 확인하거나 직접 추가하세요',

  seeMyData: '내 기록 보기',
  seeOrEdit: '다이빙 기록 보기 및 수정',
  inCardForSocials: 'SNS 공유용 카드로 만들기',

  diveAdded: '로그북에 다이빙이 추가됐어요!',
  whatNow: '이제 무엇을 할까요?',
  seeInLogbook: '내 로그북에서 보기',
  shareOnSocials: 'SNS에 공유하기',
  backToActivities: '액티비티로 돌아가기',

  divingAt: (site) => `${site}에서 다이빙`,
  min: '분',
  tempShort: '수온',
  cardDate1: '2026. 2. 26.',
  newRecord: '개인 최고 기록',
  maxDepth: '최대 수심',
  prevRecord: (site) => `이전 기록 38m · 다이빙 #47 · ${site}`,
  cardDate2: '2026. 9. 16.',
  milestone: '마일스톤 달성',
  unitDives: '회',
  divingSince: '2019년부터 다이빙 · 포인트 34곳 · 6개국',
  underwater: '수중 시간',
  deepest: '최대 수심',
  diveNumberAt: (site) => `${site}에서 100번째 다이빙`,
  theTrip: '다이빙 여행',
  tripTitle: '몰디브 2025',
  divesCap: '다이빙',
  sitesCap: '포인트',
  tripLife: '만타 · 고래상어 · 거북이',
  cardDate3: '2025년 2월',
  seenIn: '전체 다이빙의 3%에서 발견',
  whaleShark: '고래상어',
  diveNo47: (site) => `다이빙 #47 · ${site}`,

  allYears: '전체',
  moonDive: '달빛 다이빙',
  lbDate1: '2026. 9. 16.',
  lbDate2: '2026. 9. 12.',
  shareThisDive: '이 다이빙 공유하기',

  profile: '프로필',
  instructor: '강사',
  diveCountHtml: (n) => `다이빙 <em>${n}</em>회`,
  myStats: '내 통계',
  diveTime: '다이빙 시간',
  maxDepthShort: '최대 수심',
  certifications: '자격증',
  countries: '국가',
  centres: '센터',
  lastDive: '최근 다이빙',
  lastDiveDate: '26년 2월',
  myCentres: '내 센터',

  activities: '액티비티',
  diveSite: '다이빙 포인트',
  upcoming: '예정된 액티비티',
  owCourse: 'Open Water — 코스',
  oneStudent: '교육생 1명',
  nextDate: '2월 28일',

  newDive: '새 다이빙',
  presetLoaded: '포인트 정보가 자동으로 입력됐어요',
  maxDepthAbbr: '최대 수심',
  minutes: (n) => `${n}분`,
  visibility: '시야',
  continue: '계속',

  qrText: '다이버가 이 QR을 스캔하면 다이빙을 기록하고 액티비티를 확인할 수 있어요. 다운로드해서 센터나 보트에 인쇄해 두세요.',
  manageTeam: '팀 관리',
  editCentre: '센터 정보 수정',

  diversInCentreHtml: (n) => `내 센터 다이버 <b>${n}</b>명`,
  diverProfile: '다이버 프로필',
  seePublicProfile: '공개 프로필 보기',
  atYourCentre: '내 센터 이용 기록',
  activityHistory: '액티비티 기록',
  diveAt: (site) => `다이빙 — ${site}`,
  recreational: '레크리에이션',
  course: '코스',
  courseAdvanced: '코스 — Advanced',
  histDate2: '2026. 2. 24.',
  histDate3: '2026. 2. 3.',

  ownerActivities: (n) => `소유자 · 액티비티 ${n}개`,
  harbour: '항구점',
  createCentre: '새 센터 만들기',
  noTeam: '아직 소속된 센터 팀이 없어요. 센터에서 추가하면 여기에 표시돼요.',

  roleOwner: '소유자',
  roleAdmin: '관리자',
  addMember: '멤버 추가',

  siteMantas: '약한 조류 · 만타',
  siteWall: '월 · 상어',
  siteCave: '동굴 · 빛내림',
  addDiveSite: '다이빙 포인트 추가',

  eventOn: '진행 중인 이벤트',
  beachCleanup: '해변 정화 활동',
  beachWhen: '9월 14일 (토) · 09:00',
  seabedCleanup: '수중 정화 활동',
  seabedWhen: '9월 21일 (일) · 08:30',
  ngoMarker: (name) => `${name} NGO`,
  kindCentre: '다이빙 센터',
  kindNgo: 'NGO',
  kindSite: '다이빙 포인트',
  kindEvent: '이벤트',
  ctaCentre: '센터 보기',
  ctaNgo: 'NGO 보기',
  ctaSite: '다이빙 포인트 보기',
  ctaEvent: '이벤트 보기',
  organiser: '주최',

  photosN: (n) => `사진 ${n}장`,
  daysLeft: (n) => `${n}일 남음`,
  yourPhoto: '내 사진',
  follow: '팔로우',

  badgeTitle: '참가 배지',
  attended: (date) => `참가 완료 · ${date}`,
  tookPart: (name) => `${name} 님이 이 이벤트에 참가했어요.`,

  logbook: 'Logbook',
  tabDives: '다이빙',
  tabCrm: 'CRM',
  myCentre: '내 센터',

  modeManage: '관리',
  modeDiver: '다이버',
  calendar: '캘린더',
  diveSitesNav: '다이빙 포인트',
  activeCentre: '현재 센터',
  tripsScheduled: '예정된 출항 3건',
  seeCentreQr: '센터 QR 보기',
  createActivity: '액티비티 만들기',
  statDivers: 'CRM 등록 다이버',
  statDives: '기록된 다이빙',
  outOf: (a, b) => `${b}개 중 ${a}개`,
  profileComplete: '공개 프로필 완성도',
  boatFunDive: '보트 다이빙 · Fun dive',
  nightFunDive: '나이트 다이빙 · Fun dive',
  participantsN: (n) => `참가자 ${n}명`,
  addParticipant: '참가자 추가',
  noAccount: '아직 계정 없음',
  today: '오늘',
  scannedQrPl: 'QR 스캔',
  addedByHandPl: '직접 추가',
  diversVisited: (n, centre) => `${centre} 방문 다이버 ${n}명`,
  lastDate: '2026. 2. 26.',
  myCentrePublic: '내 센터 · 공개 프로필',
  howDiversSeeYou: '다이버에게 보이는 모습',
  editDetails: '정보 수정',
  uniqueQr: '센터 전용 QR',
  qrWhere: '보트, 카운터, 입구에 붙여 두세요.',
  sitesMore: (site) => `${site}, Shark Point 외 4곳`,
  staff: '강사 3명 · 다이브마스터 2명',
  languages: '언어',
  units: '단위',
  unitList: '미터 · bar · °C',
  profileChecklist: ['센터 소개', '언어', '위치', '다이빙 포인트', '해양 생물', '팀', '연락처'],
  exampleData: '예시 데이터',
};

export const APP_TEXT: Record<AppLang, typeof es> = { es, en, pt, ko };
export type AppText = typeof es;

/** Para meter una cifra que llega por props dentro de un texto HTML (diveCountHtml, diversInCentreHtml). */
export const escHtml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
