/**
 * Iconos de línea (Lucide, ISC) — design system Cofundo: trazo 1.5, monocromo, 16–20 px.
 * Un único sitio: añadir un icono = una línea aquí. Se guardan solo los trazos internos del SVG.
 */
import {
  FileText, Store, GraduationCap, MessageSquareText, Trophy, BookOpen, Map, Boxes, Users, Palette, WandSparkles, Settings, ChevronRight, ChevronDown, ChevronLeft, Plus, Trash2, LogOut, Link, Copy, Eye, EyeOff, Send, Check, X, ArrowUp, ArrowDown, GripVertical, Search, Clock, TriangleAlert, Lock, UserPlus, Pencil, Archive, RotateCcw, ExternalLink, Printer, Building2, User, Globe, Brain, Target, Heart, Zap, Music, Waves, Monitor, PartyPopper, Mic, Briefcase, Handshake, Ban, ShieldAlert, Wallet, Crown, Megaphone, Smile, ChartColumn, Compass, MapPin, Tag, CircleHelp, Lightbulb, Download, Upload, Image, Menu, CircleCheck, CircleX, Info, Sparkles, Ship, Hotel, Utensils, Ticket, Mountain, Fish, Anchor, Wine, Calendar, Star, Flag, Scale, HeartHandshake, Gauge, Repeat, Layers, Filter, KeyRound, Mail, Phone, ListChecks, Route, Camera, Speaker, Gift,
} from 'lucide-static';

const inner = (svg: string) => svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();

export const ICONS = {
  'file-text': inner(FileText),
  'store': inner(Store),
  'graduation-cap': inner(GraduationCap),
  'message-square-text': inner(MessageSquareText),
  'trophy': inner(Trophy),
  'book-open': inner(BookOpen),
  'map': inner(Map),
  'boxes': inner(Boxes),
  'users': inner(Users),
  'palette': inner(Palette),
  'wand-sparkles': inner(WandSparkles),
  'settings': inner(Settings),
  'chevron-right': inner(ChevronRight),
  'chevron-down': inner(ChevronDown),
  'chevron-left': inner(ChevronLeft),
  'plus': inner(Plus),
  'trash2': inner(Trash2),
  'log-out': inner(LogOut),
  'link': inner(Link),
  'copy': inner(Copy),
  'eye': inner(Eye),
  'eye-off': inner(EyeOff),
  'send': inner(Send),
  'check': inner(Check),
  'x': inner(X),
  'arrow-up': inner(ArrowUp),
  'arrow-down': inner(ArrowDown),
  'grip-vertical': inner(GripVertical),
  'search': inner(Search),
  'clock': inner(Clock),
  'triangle-alert': inner(TriangleAlert),
  'lock': inner(Lock),
  'user-plus': inner(UserPlus),
  'pencil': inner(Pencil),
  'archive': inner(Archive),
  'rotate-ccw': inner(RotateCcw),
  'external-link': inner(ExternalLink),
  'printer': inner(Printer),
  'building2': inner(Building2),
  'user': inner(User),
  'globe': inner(Globe),
  'brain': inner(Brain),
  'target': inner(Target),
  'heart': inner(Heart),
  'zap': inner(Zap),
  'music': inner(Music),
  'waves': inner(Waves),
  'monitor': inner(Monitor),
  'party-popper': inner(PartyPopper),
  'mic': inner(Mic),
  'briefcase': inner(Briefcase),
  'handshake': inner(Handshake),
  'ban': inner(Ban),
  'shield-alert': inner(ShieldAlert),
  'wallet': inner(Wallet),
  'crown': inner(Crown),
  'megaphone': inner(Megaphone),
  'smile': inner(Smile),
  'chart-column': inner(ChartColumn),
  'compass': inner(Compass),
  'map-pin': inner(MapPin),
  'tag': inner(Tag),
  'circle-help': inner(CircleHelp),
  'lightbulb': inner(Lightbulb),
  'download': inner(Download),
  'upload': inner(Upload),
  'image': inner(Image),
  'menu': inner(Menu),
  'circle-check': inner(CircleCheck),
  'circle-x': inner(CircleX),
  'info': inner(Info),
  'sparkles': inner(Sparkles),
  'ship': inner(Ship),
  'hotel': inner(Hotel),
  'utensils': inner(Utensils),
  'ticket': inner(Ticket),
  'mountain': inner(Mountain),
  'fish': inner(Fish),
  'anchor': inner(Anchor),
  'wine': inner(Wine),
  'calendar': inner(Calendar),
  'star': inner(Star),
  'flag': inner(Flag),
  'scale': inner(Scale),
  'heart-handshake': inner(HeartHandshake),
  'gauge': inner(Gauge),
  'repeat': inner(Repeat),
  'layers': inner(Layers),
  'filter': inner(Filter),
  'key-round': inner(KeyRound),
  'mail': inner(Mail),
  'phone': inner(Phone),
  'list-checks': inner(ListChecks),
  'route': inner(Route),
  'camera': inner(Camera),
  'speaker': inner(Speaker),
  'gift': inner(Gift),
} as const;

export type IconName = keyof typeof ICONS;
export const isIconName = (x: string): x is IconName => Object.hasOwn(ICONS, x);

/** SVG completo (para {@html} en Svelte o set:html en Astro). */
export function iconSvg(name: IconName, size = 18, label?: string): string {
  const a11y = label ? `role="img" aria-label="${label.replace(/"/g, '&quot;')}"` : 'aria-hidden="true"';
  return `<svg class="co-icon" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" ${a11y}>${ICONS[name]}</svg>`;
}
